// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CougarControlV3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SpinFwdFast_Animation(lv_obj_t * TargetObject, int delay);
void ControlPanelRight_Animation(lv_obj_t * TargetObject, int delay);
void ControlPanelLeft_Animation(lv_obj_t * TargetObject, int delay);
void ContactorONOFF_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Scr1InnovatumImage;
void ui_event_Scr1TouchToStartButton(lv_event_t * e);
lv_obj_t * ui_Scr1TouchToStartButton;
lv_obj_t * ui_Scr1TouchToStartLabel;
lv_obj_t * ui_CougarControlLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_ROVStaticPanel;
lv_obj_t * ui_Scr2ROVStaticImage;
lv_obj_t * ui_PFThrusterStatic;
lv_obj_t * ui_PFThrusterSpinning;
lv_obj_t * ui_SFThrusterStatic;
lv_obj_t * ui_SFThrusterSpinning;
lv_obj_t * ui_PAThrusterStatic;
lv_obj_t * ui_PAThrusterSpinning;
lv_obj_t * ui_SAThrusterStatic;
lv_obj_t * ui_SAThrusterSpinning;
lv_obj_t * ui_PVThrusterStatic;
lv_obj_t * ui_PVThrusterSpinning;
lv_obj_t * ui_SVThrusterStatic;
lv_obj_t * ui_SVThrusterSpinning;
lv_obj_t * ui_VehicleLiveLabel;
lv_obj_t * ui_Scr2ControlPanel;
lv_obj_t * ui_PSUPanel;
lv_obj_t * ui_MainContactor;
lv_obj_t * ui_MainContactorIndicatorBarOFF;
lv_obj_t * ui_MainContactorIndicatorBarON;
lv_obj_t * ui_PSUStartButtonLabel;
lv_obj_t * ui_PSUONLabel;
lv_obj_t * ui_PSUONLabel1;
lv_obj_t * ui_PSUDCVoltLabel;
lv_obj_t * ui_PSUDCAMPLabel;
lv_obj_t * ui_PSUVALabel;
lv_obj_t * ui_PSUPOWERLED;
lv_obj_t * ui_PSUStartButton;
lv_obj_t * ui_PDUPanel;
lv_obj_t * ui_ACSurfaceSwitch;
lv_obj_t * ui_ACSurfaceLabel;
lv_obj_t * ui_ACSurfaceLED;
lv_obj_t * ui_ACVehicleSwitch;
lv_obj_t * ui_ACVehicleLabel;
lv_obj_t * ui_ACVehicleLED;
lv_obj_t * ui_DC1Label;
lv_obj_t * ui_DC1Switch;
lv_obj_t * ui_DC2Label;
lv_obj_t * ui_DC1LED;
lv_obj_t * ui_DC2Switch;
lv_obj_t * ui_DC2LED;
lv_obj_t * ui_DC1DC2Line;
lv_obj_t * ui_MasterDCSwitch;
lv_obj_t * ui_MasterDCSwitchLabel;
lv_obj_t * ui_MasterDCLed;
lv_obj_t * ui_ThrustersEnabledSwitch;
lv_obj_t * ui_ThrustersEnabledSwitchLabel;
lv_obj_t * ui_ThrustersEnabledLed;
void ui_event_Scr2Button1(lv_event_t * e);
lv_obj_t * ui_Scr2Button1;
lv_obj_t * ui_Scr2Button1Label;
void ui_event_Scr2Button2(lv_event_t * e);
lv_obj_t * ui_Scr2Button2;
lv_obj_t * ui_Scr2Button2Label;
void ui_event_Scr2Button3(lv_event_t * e);
lv_obj_t * ui_Scr2Button3;
lv_obj_t * ui_Scr2Button3Label;
void ui_event_Scr2Button4(lv_event_t * e);
lv_obj_t * ui_Scr2Button4;
lv_obj_t * ui_Scr2Button4Label;
lv_obj_t * ui_Scr2InfoPanel;
lv_obj_t * ui_InfoLabel1;
lv_obj_t * ui_InfoLabel2;
void ui_event_HideControlPanelIcon(lv_event_t * e);
lv_obj_t * ui_HideControlPanelIcon;
void ui_event_ShowControlPanelIcon(lv_event_t * e);
lv_obj_t * ui_ShowControlPanelIcon;
lv_obj_t * ui_ScrHCUPanel;
lv_obj_t * ui_HCUPanel1;
lv_obj_t * ui_HCUPanel2;
lv_obj_t * ui_FRSetArc;
lv_obj_t * ui_SpeedArc;
lv_obj_t * ui_TurnsSetArc;
lv_obj_t * ui_TurnRateArc;
lv_obj_t * ui_LatSetArc;
lv_obj_t * ui_LatSpeedArc;
lv_obj_t * ui_FRSetLabel;
lv_obj_t * ui_SpeedLabel;
lv_obj_t * ui_TurnRateLabel;
lv_obj_t * ui_TurnSetLabel;
lv_obj_t * ui_LatSetLabel;
lv_obj_t * ui_LatSpeedLabel;
lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SpinFwdFast_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 400);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void ControlPanelRight_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 130);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void ControlPanelLeft_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 225, 95);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void ContactorONOFF_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Scr1TouchToStartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_Scr2Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PFThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SFThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PAThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SAThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        SpinFwdFast_Animation(ui_PFThrusterSpinning, 0);
        SpinFwdFast_Animation(ui_SFThrusterSpinning, 0);
        SpinFwdFast_Animation(ui_PAThrusterSpinning, 0);
        SpinFwdFast_Animation(ui_SAThrusterSpinning, 0);
        _ui_flag_modify(ui_PFThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SFThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PAThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SAThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Scr2Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PFThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SFThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PAThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SAThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PFThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SFThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PAThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SAThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Scr2Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PVThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SVThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        SpinFwdFast_Animation(ui_PVThrusterSpinning, 0);
        SpinFwdFast_Animation(ui_SVThrusterSpinning, 0);
        _ui_flag_modify(ui_PVThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SVThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Scr2Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PVThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SVThrusterStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_PVThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SVThrusterSpinning, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_HideControlPanelIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ControlPanelRight_Animation(ui_Scr2ControlPanel, 0);
        _ui_flag_modify(ui_HideControlPanelIcon, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ShowControlPanelIcon, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ShowControlPanelIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ControlPanelLeft_Animation(ui_Scr2ControlPanel, 0);
        _ui_flag_modify(ui_ShowControlPanelIcon, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_HideControlPanelIcon, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
