// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CougarControlV3

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scr1InnovatumImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Scr1InnovatumImage, &ui_img_innovatum_logo_email_png);
    lv_obj_set_width(ui_Scr1InnovatumImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr1InnovatumImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr1InnovatumImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr1InnovatumImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Scr1InnovatumImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scr1TouchToStartButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Scr1TouchToStartButton, 300);
    lv_obj_set_height(ui_Scr1TouchToStartButton, 200);
    lv_obj_set_align(ui_Scr1TouchToStartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr1TouchToStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scr1TouchToStartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr1TouchToStartButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr1TouchToStartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr1TouchToStartLabel = lv_label_create(ui_Scr1TouchToStartButton);
    lv_obj_set_width(ui_Scr1TouchToStartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr1TouchToStartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scr1TouchToStartLabel, 0);
    lv_obj_set_y(ui_Scr1TouchToStartLabel, 50);
    lv_obj_set_align(ui_Scr1TouchToStartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scr1TouchToStartLabel, "Touch To Start");
    lv_obj_set_style_text_color(ui_Scr1TouchToStartLabel, lv_color_hex(0x00B7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scr1TouchToStartLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scr1TouchToStartLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CougarControlLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CougarControlLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CougarControlLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CougarControlLabel, 0);
    lv_obj_set_y(ui_CougarControlLabel, -50);
    lv_obj_set_align(ui_CougarControlLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CougarControlLabel, "Cougar Control V2");
    lv_obj_set_style_text_color(ui_CougarControlLabel, lv_color_hex(0x00B7E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CougarControlLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CougarControlLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Scr1TouchToStartButton, ui_event_Scr1TouchToStartButton, LV_EVENT_ALL, NULL);

}
