// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CougarControlV3

#ifndef _COUGARCONTROLV3_UI_H
#define _COUGARCONTROLV3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void SpinFwdFast_Animation(lv_obj_t * TargetObject, int delay);
void ControlPanelRight_Animation(lv_obj_t * TargetObject, int delay);
void ControlPanelLeft_Animation(lv_obj_t * TargetObject, int delay);
void ContactorONOFF_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Scr1InnovatumImage;
void ui_event_Scr1TouchToStartButton(lv_event_t * e);
extern lv_obj_t * ui_Scr1TouchToStartButton;
extern lv_obj_t * ui_Scr1TouchToStartLabel;
extern lv_obj_t * ui_CougarControlLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ROVStaticPanel;
extern lv_obj_t * ui_Scr2ROVStaticImage;
extern lv_obj_t * ui_PFThrusterStatic;
extern lv_obj_t * ui_PFThrusterSpinning;
extern lv_obj_t * ui_SFThrusterStatic;
extern lv_obj_t * ui_SFThrusterSpinning;
extern lv_obj_t * ui_PAThrusterStatic;
extern lv_obj_t * ui_PAThrusterSpinning;
extern lv_obj_t * ui_SAThrusterStatic;
extern lv_obj_t * ui_SAThrusterSpinning;
extern lv_obj_t * ui_PVThrusterStatic;
extern lv_obj_t * ui_PVThrusterSpinning;
extern lv_obj_t * ui_SVThrusterStatic;
extern lv_obj_t * ui_SVThrusterSpinning;
extern lv_obj_t * ui_VehicleLiveLabel;
extern lv_obj_t * ui_Scr2ControlPanel;
extern lv_obj_t * ui_PSUPanel;
extern lv_obj_t * ui_MainContactor;
extern lv_obj_t * ui_MainContactorIndicatorBarOFF;
extern lv_obj_t * ui_MainContactorIndicatorBarON;
extern lv_obj_t * ui_PSUStartButtonLabel;
extern lv_obj_t * ui_PSUONLabel;
extern lv_obj_t * ui_PSUONLabel1;
extern lv_obj_t * ui_PSUDCVoltLabel;
extern lv_obj_t * ui_PSUDCAMPLabel;
extern lv_obj_t * ui_PSUVALabel;
extern lv_obj_t * ui_PSUPOWERLED;
extern lv_obj_t * ui_PSUStartButton;
extern lv_obj_t * ui_PDUPanel;
extern lv_obj_t * ui_ACSurfaceSwitch;
extern lv_obj_t * ui_ACSurfaceLabel;
extern lv_obj_t * ui_ACSurfaceLED;
extern lv_obj_t * ui_ACVehicleSwitch;
extern lv_obj_t * ui_ACVehicleLabel;
extern lv_obj_t * ui_ACVehicleLED;
extern lv_obj_t * ui_DC1Label;
extern lv_obj_t * ui_DC1Switch;
extern lv_obj_t * ui_DC2Label;
extern lv_obj_t * ui_DC1LED;
extern lv_obj_t * ui_DC2Switch;
extern lv_obj_t * ui_DC2LED;
extern lv_obj_t * ui_DC1DC2Line;
extern lv_obj_t * ui_MasterDCSwitch;
extern lv_obj_t * ui_MasterDCSwitchLabel;
extern lv_obj_t * ui_MasterDCLed;
extern lv_obj_t * ui_ThrustersEnabledSwitch;
extern lv_obj_t * ui_ThrustersEnabledSwitchLabel;
extern lv_obj_t * ui_ThrustersEnabledLed;
void ui_event_Scr2Button1(lv_event_t * e);
extern lv_obj_t * ui_Scr2Button1;
extern lv_obj_t * ui_Scr2Button1Label;
void ui_event_Scr2Button2(lv_event_t * e);
extern lv_obj_t * ui_Scr2Button2;
extern lv_obj_t * ui_Scr2Button2Label;
void ui_event_Scr2Button3(lv_event_t * e);
extern lv_obj_t * ui_Scr2Button3;
extern lv_obj_t * ui_Scr2Button3Label;
void ui_event_Scr2Button4(lv_event_t * e);
extern lv_obj_t * ui_Scr2Button4;
extern lv_obj_t * ui_Scr2Button4Label;
extern lv_obj_t * ui_Scr2InfoPanel;
extern lv_obj_t * ui_InfoLabel1;
extern lv_obj_t * ui_InfoLabel2;
void ui_event_HideControlPanelIcon(lv_event_t * e);
extern lv_obj_t * ui_HideControlPanelIcon;
void ui_event_ShowControlPanelIcon(lv_event_t * e);
extern lv_obj_t * ui_ShowControlPanelIcon;
extern lv_obj_t * ui_ScrHCUPanel;
extern lv_obj_t * ui_HCUPanel1;
extern lv_obj_t * ui_HCUPanel2;
extern lv_obj_t * ui_FRSetArc;
extern lv_obj_t * ui_SpeedArc;
extern lv_obj_t * ui_TurnsSetArc;
extern lv_obj_t * ui_TurnRateArc;
extern lv_obj_t * ui_LatSetArc;
extern lv_obj_t * ui_LatSpeedArc;
extern lv_obj_t * ui_FRSetLabel;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_TurnRateLabel;
extern lv_obj_t * ui_TurnSetLabel;
extern lv_obj_t * ui_LatSetLabel;
extern lv_obj_t * ui_LatSpeedLabel;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_innovatum_logo_email_png);    // assets/Innovatum Logo email.png
LV_IMG_DECLARE(ui_img_cougarv6shape_png);    // assets/CougarV6Shape.png
LV_IMG_DECLARE(ui_img_blackthruster32x32_png);    // assets/BlackThruster32x32.png
LV_IMG_DECLARE(ui_img_configicongrey_png);    // assets/ConfigIconGrey.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
