// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: CougarControlV3

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ROVStaticPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ROVStaticPanel, 180);
    lv_obj_set_height(ui_ROVStaticPanel, lv_pct(100));
    lv_obj_set_align(ui_ROVStaticPanel, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_ROVStaticPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ROVStaticPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ROVStaticPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ROVStaticPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ROVStaticPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2ROVStaticImage = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_Scr2ROVStaticImage, &ui_img_cougarv6shape_png);
    lv_obj_set_width(ui_Scr2ROVStaticImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2ROVStaticImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr2ROVStaticImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2ROVStaticImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Scr2ROVStaticImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Scr2ROVStaticImage, 200);

    ui_PFThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PFThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PFThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PFThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PFThrusterStatic, -40);
    lv_obj_set_y(ui_PFThrusterStatic, -68);
    lv_obj_set_align(ui_PFThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PFThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PFThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PFThrusterStatic, 200);

    ui_PFThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PFThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PFThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PFThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PFThrusterSpinning, -40);
    lv_obj_set_y(ui_PFThrusterSpinning, -68);
    lv_obj_set_align(ui_PFThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PFThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PFThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PFThrusterSpinning, 200);

    ui_SFThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SFThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SFThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SFThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SFThrusterStatic, 40);
    lv_obj_set_y(ui_SFThrusterStatic, -68);
    lv_obj_set_align(ui_SFThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SFThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SFThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SFThrusterStatic, 200);

    ui_SFThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SFThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SFThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SFThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SFThrusterSpinning, 40);
    lv_obj_set_y(ui_SFThrusterSpinning, -68);
    lv_obj_set_align(ui_SFThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SFThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SFThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SFThrusterSpinning, 200);

    ui_PAThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PAThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PAThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PAThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PAThrusterStatic, -40);
    lv_obj_set_y(ui_PAThrusterStatic, 71);
    lv_obj_set_align(ui_PAThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PAThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PAThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PAThrusterStatic, 200);

    ui_PAThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PAThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PAThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PAThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PAThrusterSpinning, -40);
    lv_obj_set_y(ui_PAThrusterSpinning, 71);
    lv_obj_set_align(ui_PAThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PAThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PAThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PAThrusterSpinning, 200);

    ui_SAThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SAThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SAThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SAThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SAThrusterStatic, 40);
    lv_obj_set_y(ui_SAThrusterStatic, 71);
    lv_obj_set_align(ui_SAThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SAThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SAThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SAThrusterStatic, 200);

    ui_SAThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SAThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SAThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SAThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SAThrusterSpinning, 40);
    lv_obj_set_y(ui_SAThrusterSpinning, 71);
    lv_obj_set_align(ui_SAThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SAThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SAThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SAThrusterSpinning, 200);

    ui_PVThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PVThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PVThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PVThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PVThrusterStatic, -32);
    lv_obj_set_y(ui_PVThrusterStatic, 2);
    lv_obj_set_align(ui_PVThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PVThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PVThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PVThrusterStatic, 200);

    ui_PVThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_PVThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_PVThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PVThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PVThrusterSpinning, -32);
    lv_obj_set_y(ui_PVThrusterSpinning, 2);
    lv_obj_set_align(ui_PVThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PVThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PVThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PVThrusterSpinning, 200);

    ui_SVThrusterStatic = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SVThrusterStatic, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SVThrusterStatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SVThrusterStatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SVThrusterStatic, 33);
    lv_obj_set_y(ui_SVThrusterStatic, 2);
    lv_obj_set_align(ui_SVThrusterStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SVThrusterStatic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SVThrusterStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SVThrusterStatic, 200);

    ui_SVThrusterSpinning = lv_img_create(ui_ROVStaticPanel);
    lv_img_set_src(ui_SVThrusterSpinning, &ui_img_blackthruster32x32_png);
    lv_obj_set_width(ui_SVThrusterSpinning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SVThrusterSpinning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SVThrusterSpinning, 33);
    lv_obj_set_y(ui_SVThrusterSpinning, 2);
    lv_obj_set_align(ui_SVThrusterSpinning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SVThrusterSpinning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SVThrusterSpinning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SVThrusterSpinning, 200);

    ui_ShowControlButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ShowControlButton, 120);
    lv_obj_set_height(ui_ShowControlButton, 20);
    lv_obj_set_x(ui_ShowControlButton, -5);
    lv_obj_set_y(ui_ShowControlButton, -108);
    lv_obj_set_align(ui_ShowControlButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ShowControlButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShowControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShowControlButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShowControlButton, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShowControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ShowControlButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ShowControlButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ShowControlButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ShowControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ShowControlButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ShowControlButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShowControlLabel = lv_label_create(ui_ShowControlButton);
    lv_obj_set_width(ui_ShowControlLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShowControlLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShowControlLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShowControlLabel, "SHOW CONTROL");
    lv_obj_set_style_text_color(ui_ShowControlLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ShowControlLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ShowControlLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HideControlButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_HideControlButton, 120);
    lv_obj_set_height(ui_HideControlButton, 20);
    lv_obj_set_x(ui_HideControlButton, -5);
    lv_obj_set_y(ui_HideControlButton, -108);
    lv_obj_set_align(ui_HideControlButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_HideControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HideControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HideControlButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HideControlButton, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HideControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HideControlButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HideControlButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_HideControlButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HideControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HideControlButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HideControlButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HideControlLabel = lv_label_create(ui_HideControlButton);
    lv_obj_set_width(ui_HideControlLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HideControlLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HideControlLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HideControlLabel, "HIDE CONTROL");
    lv_obj_set_style_text_color(ui_HideControlLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HideControlLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HideControlLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2ControlPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2ControlPanel, 120);
    lv_obj_set_height(ui_Scr2ControlPanel, 195);
    lv_obj_set_x(ui_Scr2ControlPanel, 95);
    lv_obj_set_y(ui_Scr2ControlPanel, 0);
    lv_obj_set_align(ui_Scr2ControlPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Scr2ControlPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Scr2ControlPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scr2ControlPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Scr2ControlPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Scr2ControlPanel, lv_color_hex(0x555E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2ControlPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2ControlPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Scr2ControlPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Scr2ControlPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Scr2ControlPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Scr2ControlPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Scr2ControlPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Scr2ControlPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUPanel = lv_obj_create(ui_Scr2ControlPanel);
    lv_obj_set_width(ui_PSUPanel, 112);
    lv_obj_set_height(ui_PSUPanel, 40);
    lv_obj_set_align(ui_PSUPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PSUPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainContactor = lv_btn_create(ui_PSUPanel);
    lv_obj_set_width(ui_MainContactor, 22);
    lv_obj_set_height(ui_MainContactor, 22);
    lv_obj_set_x(ui_MainContactor, -35);
    lv_obj_set_y(ui_MainContactor, 0);
    lv_obj_set_align(ui_MainContactor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainContactor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainContactor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainContactor, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainContactor, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContactor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContactorIndicatorBarOFF = lv_bar_create(ui_MainContactor);
    lv_bar_set_value(ui_MainContactorIndicatorBarOFF, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MainContactorIndicatorBarOFF, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainContactorIndicatorBarOFF, 15);
    lv_obj_set_height(ui_MainContactorIndicatorBarOFF, 5);
    lv_obj_set_x(ui_MainContactorIndicatorBarOFF, 10);
    lv_obj_set_y(ui_MainContactorIndicatorBarOFF, 0);
    lv_obj_set_align(ui_MainContactorIndicatorBarOFF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainContactorIndicatorBarOFF, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_transform_angle(ui_MainContactorIndicatorBarOFF, 1200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainContactorIndicatorBarOFF, lv_color_hex(0xFFFFFF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContactorIndicatorBarOFF, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MainContactorIndicatorBarON = lv_bar_create(ui_MainContactor);
    lv_bar_set_value(ui_MainContactorIndicatorBarON, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MainContactorIndicatorBarON, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MainContactorIndicatorBarON, 15);
    lv_obj_set_height(ui_MainContactorIndicatorBarON, 5);
    lv_obj_set_x(ui_MainContactorIndicatorBarON, 8);
    lv_obj_set_y(ui_MainContactorIndicatorBarON, 4);
    lv_obj_set_align(ui_MainContactorIndicatorBarON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainContactorIndicatorBarON, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_transform_angle(ui_MainContactorIndicatorBarON, 2200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MainContactorIndicatorBarON, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContactorIndicatorBarON, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PSUStartButtonLabel = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUStartButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUStartButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUStartButtonLabel, -5);
    lv_obj_set_y(ui_PSUStartButtonLabel, 12);
    lv_obj_set_align(ui_PSUStartButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUStartButtonLabel, "Start");
    lv_obj_set_style_text_font(ui_PSUStartButtonLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUONLabel = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUONLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUONLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUONLabel, -45);
    lv_obj_set_y(ui_PSUONLabel, -14);
    lv_obj_set_align(ui_PSUONLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUONLabel, "ON");
    lv_obj_set_style_text_font(ui_PSUONLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUONLabel1 = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUONLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUONLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUONLabel1, -45);
    lv_obj_set_y(ui_PSUONLabel1, 14);
    lv_obj_set_align(ui_PSUONLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUONLabel1, "OFF");
    lv_obj_set_style_text_font(ui_PSUONLabel1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUDCVoltLabel = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUDCVoltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUDCVoltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUDCVoltLabel, 36);
    lv_obj_set_y(ui_PSUDCVoltLabel, -10);
    lv_obj_set_align(ui_PSUDCVoltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUDCVoltLabel, "---");
    lv_obj_set_style_text_color(ui_PSUDCVoltLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSUDCVoltLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSUDCVoltLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSUDCVoltLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSUDCVoltLabel, lv_color_hex(0xD7C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSUDCVoltLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUDCAMPLabel = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUDCAMPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUDCAMPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUDCAMPLabel, 36);
    lv_obj_set_y(ui_PSUDCAMPLabel, 10);
    lv_obj_set_align(ui_PSUDCAMPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUDCAMPLabel, "---");
    lv_obj_set_style_text_color(ui_PSUDCAMPLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSUDCAMPLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSUDCAMPLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSUDCAMPLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSUDCAMPLabel, lv_color_hex(0xD7C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSUDCAMPLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUVALabel = lv_label_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUVALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PSUVALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PSUVALabel, 15);
    lv_obj_set_y(ui_PSUVALabel, 0);
    lv_obj_set_align(ui_PSUVALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSUVALabel, "V\nA");
    lv_obj_set_style_text_font(ui_PSUVALabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUPOWERLED = lv_btn_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUPOWERLED, 10);
    lv_obj_set_height(ui_PSUPOWERLED, 10);
    lv_obj_set_x(ui_PSUPOWERLED, -18);
    lv_obj_set_y(ui_PSUPOWERLED, -12);
    lv_obj_set_align(ui_PSUPOWERLED, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PSUPOWERLED, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSUPOWERLED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PSUPOWERLED, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSUPOWERLED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSUStartButton = lv_btn_create(ui_PSUPanel);
    lv_obj_set_width(ui_PSUStartButton, 15);
    lv_obj_set_height(ui_PSUStartButton, 15);
    lv_obj_set_x(ui_PSUStartButton, -5);
    lv_obj_set_y(ui_PSUStartButton, 0);
    lv_obj_set_align(ui_PSUStartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PSUStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSUStartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSUStartButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSUStartButton, lv_color_hex(0x035103), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSUStartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PSUStartButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PSUStartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PSUStartButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PSUStartButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSUStartButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PSUStartButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_PSUStartButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PSUStartButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PDUPanel = lv_obj_create(ui_Scr2ControlPanel);
    lv_obj_set_width(ui_PDUPanel, 112);
    lv_obj_set_height(ui_PDUPanel, 143);
    lv_obj_set_x(ui_PDUPanel, -35);
    lv_obj_set_y(ui_PDUPanel, -32);
    lv_obj_set_align(ui_PDUPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PDUPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ACSurfaceSwitch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACSurfaceSwitch, 22);
    lv_obj_set_height(ui_ACSurfaceSwitch, 12);
    lv_obj_set_x(ui_ACSurfaceSwitch, -22);
    lv_obj_set_y(ui_ACSurfaceSwitch, -35);
    lv_obj_set_align(ui_ACSurfaceSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ACSurfaceSwitch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACSurfaceSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_ACSurfaceSwitch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ACSurfaceSwitch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ACSurfaceSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_ACSurfaceSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACSurfaceSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ACSurfaceLabel = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACSurfaceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACSurfaceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACSurfaceLabel, -37);
    lv_obj_set_y(ui_ACSurfaceLabel, -52);
    lv_obj_set_align(ui_ACSurfaceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ACSurfaceLabel, "    AC \nSurface");
    lv_obj_set_style_text_font(ui_ACSurfaceLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACSurfaceLED = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACSurfaceLED, 10);
    lv_obj_set_height(ui_ACSurfaceLED, 10);
    lv_obj_set_x(ui_ACSurfaceLED, -24);
    lv_obj_set_y(ui_ACSurfaceLED, -55);
    lv_obj_set_align(ui_ACSurfaceLED, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACSurfaceLED, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ACSurfaceLED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ACSurfaceLED, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACSurfaceLED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACVehicleSwitch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACVehicleSwitch, 22);
    lv_obj_set_height(ui_ACVehicleSwitch, 12);
    lv_obj_set_x(ui_ACVehicleSwitch, 15);
    lv_obj_set_y(ui_ACVehicleSwitch, -35);
    lv_obj_set_align(ui_ACVehicleSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ACVehicleSwitch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACVehicleSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_ACVehicleSwitch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ACVehicleSwitch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ACVehicleSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_ACVehicleSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACVehicleSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ACVehicleLabel = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACVehicleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ACVehicleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ACVehicleLabel, -1);
    lv_obj_set_y(ui_ACVehicleLabel, -52);
    lv_obj_set_align(ui_ACVehicleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ACVehicleLabel, "    AC \nVehicle");
    lv_obj_set_style_text_font(ui_ACVehicleLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACVehicleLED = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_ACVehicleLED, 10);
    lv_obj_set_height(ui_ACVehicleLED, 10);
    lv_obj_set_x(ui_ACVehicleLED, 13);
    lv_obj_set_y(ui_ACVehicleLED, -55);
    lv_obj_set_align(ui_ACVehicleLED, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACVehicleLED, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ACVehicleLED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ACVehicleLED, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACVehicleLED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DC1Label = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DC1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DC1Label, -37);
    lv_obj_set_y(ui_DC1Label, -7);
    lv_obj_set_align(ui_DC1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DC1Label, "DC 1\n");
    lv_obj_set_style_text_font(ui_DC1Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DC1Switch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC1Switch, 22);
    lv_obj_set_height(ui_DC1Switch, 12);
    lv_obj_set_x(ui_DC1Switch, -22);
    lv_obj_set_y(ui_DC1Switch, 3);
    lv_obj_set_align(ui_DC1Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DC1Switch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC1Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_DC1Switch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DC1Switch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DC1Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_DC1Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC1Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DC2Label = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DC2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DC2Label, -1);
    lv_obj_set_y(ui_DC2Label, -7);
    lv_obj_set_align(ui_DC2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DC2Label, "DC 2\n");
    lv_obj_set_style_text_font(ui_DC2Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DC1LED = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC1LED, 10);
    lv_obj_set_height(ui_DC1LED, 10);
    lv_obj_set_x(ui_DC1LED, -20);
    lv_obj_set_y(ui_DC1LED, -10);
    lv_obj_set_align(ui_DC1LED, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DC1LED, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DC1LED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DC1LED, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC1LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DC2Switch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC2Switch, 22);
    lv_obj_set_height(ui_DC2Switch, 12);
    lv_obj_set_x(ui_DC2Switch, 15);
    lv_obj_set_y(ui_DC2Switch, 3);
    lv_obj_set_align(ui_DC2Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DC2Switch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC2Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_DC2Switch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DC2Switch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_DC2Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_DC2Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC2Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_DC2LED = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_DC2LED, 10);
    lv_obj_set_height(ui_DC2LED, 10);
    lv_obj_set_x(ui_DC2LED, 16);
    lv_obj_set_y(ui_DC2LED, -10);
    lv_obj_set_align(ui_DC2LED, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DC2LED, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DC2LED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DC2LED, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC2LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DC1DC2Line = lv_bar_create(ui_PDUPanel);
    lv_bar_set_value(ui_DC1DC2Line, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_DC1DC2Line, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_DC1DC2Line, 20);
    lv_obj_set_height(ui_DC1DC2Line, 2);
    lv_obj_set_x(ui_DC1DC2Line, -20);
    lv_obj_set_y(ui_DC1DC2Line, 9);
    lv_obj_set_align(ui_DC1DC2Line, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_DC1DC2Line, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC1DC2Line, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MasterDCSwitch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_MasterDCSwitch, 35);
    lv_obj_set_height(ui_MasterDCSwitch, 18);
    lv_obj_set_x(ui_MasterDCSwitch, 59);
    lv_obj_set_y(ui_MasterDCSwitch, -15);
    lv_obj_set_align(ui_MasterDCSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MasterDCSwitch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterDCSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_MasterDCSwitch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MasterDCSwitch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MasterDCSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_MasterDCSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterDCSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MasterDCSwitchLabel = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_MasterDCSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterDCSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterDCSwitchLabel, 33);
    lv_obj_set_y(ui_MasterDCSwitchLabel, -35);
    lv_obj_set_align(ui_MasterDCSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterDCSwitchLabel, "MASTER\n     DC");
    lv_obj_set_style_text_font(ui_MasterDCSwitchLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterDCLed = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_MasterDCLed, 12);
    lv_obj_set_height(ui_MasterDCLed, 12);
    lv_obj_set_x(ui_MasterDCLed, 47);
    lv_obj_set_y(ui_MasterDCLed, -28);
    lv_obj_set_align(ui_MasterDCLed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MasterDCLed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MasterDCLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MasterDCLed, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterDCLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThrustersEnabledSwitch = lv_switch_create(ui_PDUPanel);
    lv_obj_set_width(ui_ThrustersEnabledSwitch, 35);
    lv_obj_set_height(ui_ThrustersEnabledSwitch, 18);
    lv_obj_set_x(ui_ThrustersEnabledSwitch, 50);
    lv_obj_set_y(ui_ThrustersEnabledSwitch, 43);
    lv_obj_set_align(ui_ThrustersEnabledSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ThrustersEnabledSwitch, lv_color_hex(0x525D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrustersEnabledSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_ThrustersEnabledSwitch, 4500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ThrustersEnabledSwitch, lv_color_hex(0x878D8C), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ThrustersEnabledSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_ThrustersEnabledSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrustersEnabledSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ThrustersEnabledSwitchLabel = lv_label_create(ui_PDUPanel);
    lv_obj_set_width(ui_ThrustersEnabledSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrustersEnabledSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThrustersEnabledSwitchLabel, 30);
    lv_obj_set_y(ui_ThrustersEnabledSwitchLabel, 20);
    lv_obj_set_align(ui_ThrustersEnabledSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrustersEnabledSwitchLabel, "Thrusters\nEnabled");
    lv_obj_set_style_text_font(ui_ThrustersEnabledSwitchLabel, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThrustersEnabledLed = lv_btn_create(ui_PDUPanel);
    lv_obj_set_width(ui_ThrustersEnabledLed, 12);
    lv_obj_set_height(ui_ThrustersEnabledLed, 12);
    lv_obj_set_x(ui_ThrustersEnabledLed, 45);
    lv_obj_set_y(ui_ThrustersEnabledLed, 40);
    lv_obj_set_align(ui_ThrustersEnabledLed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThrustersEnabledLed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ThrustersEnabledLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ThrustersEnabledLed, lv_color_hex(0x5E5D62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrustersEnabledLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2Button1, 40);
    lv_obj_set_height(ui_Scr2Button1, 20);
    lv_obj_set_x(ui_Scr2Button1, 13);
    lv_obj_set_y(ui_Scr2Button1, -36);
    lv_obj_set_align(ui_Scr2Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scr2Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr2Button1, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Scr2Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button1Label = lv_label_create(ui_Scr2Button1);
    lv_obj_set_width(ui_Scr2Button1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2Button1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr2Button1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scr2Button1Label, "FWD");
    lv_obj_set_style_text_color(ui_Scr2Button1Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scr2Button1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scr2Button1Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2Button2, 40);
    lv_obj_set_height(ui_Scr2Button2, 20);
    lv_obj_set_x(ui_Scr2Button2, 14);
    lv_obj_set_y(ui_Scr2Button2, -12);
    lv_obj_set_align(ui_Scr2Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scr2Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr2Button2, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Scr2Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button2Label = lv_label_create(ui_Scr2Button2);
    lv_obj_set_width(ui_Scr2Button2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2Button2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr2Button2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scr2Button2Label, "F-STOP");
    lv_obj_set_style_text_color(ui_Scr2Button2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scr2Button2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scr2Button2Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2Button3, 40);
    lv_obj_set_height(ui_Scr2Button3, 20);
    lv_obj_set_x(ui_Scr2Button3, 14);
    lv_obj_set_y(ui_Scr2Button3, 22);
    lv_obj_set_align(ui_Scr2Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scr2Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr2Button3, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Scr2Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button3Label = lv_label_create(ui_Scr2Button3);
    lv_obj_set_width(ui_Scr2Button3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2Button3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr2Button3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scr2Button3Label, "UP");
    lv_obj_set_style_text_color(ui_Scr2Button3Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scr2Button3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scr2Button3Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2Button4, 40);
    lv_obj_set_height(ui_Scr2Button4, 20);
    lv_obj_set_x(ui_Scr2Button4, 14);
    lv_obj_set_y(ui_Scr2Button4, 45);
    lv_obj_set_align(ui_Scr2Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scr2Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr2Button4, lv_color_hex(0xFFC200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Scr2Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2Button4Label = lv_label_create(ui_Scr2Button4);
    lv_obj_set_width(ui_Scr2Button4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2Button4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scr2Button4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scr2Button4Label, "U-STOP");
    lv_obj_set_style_text_color(ui_Scr2Button4Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scr2Button4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scr2Button4Label, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2InoPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Scr2InoPanel, 120);
    lv_obj_set_height(ui_Scr2InoPanel, 15);
    lv_obj_set_x(ui_Scr2InoPanel, 95);
    lv_obj_set_y(ui_Scr2InoPanel, 107);
    lv_obj_set_align(ui_Scr2InoPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scr2InoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scr2InoPanel, lv_color_hex(0x555E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scr2InoPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Scr2InoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Scr2InoPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scr2ConfigIcon = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Scr2ConfigIcon, &ui_img_configicongrey_png);
    lv_obj_set_width(ui_Scr2ConfigIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scr2ConfigIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scr2ConfigIcon, 20);
    lv_obj_set_y(ui_Scr2ConfigIcon, -106);
    lv_obj_set_align(ui_Scr2ConfigIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scr2ConfigIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Scr2ConfigIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Scr2ConfigIcon, 125);

    lv_obj_add_event_cb(ui_ShowControlButton, ui_event_ShowControlButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HideControlButton, ui_event_HideControlButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scr2Button1, ui_event_Scr2Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scr2Button2, ui_event_Scr2Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scr2Button3, ui_event_Scr2Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scr2Button4, ui_event_Scr2Button4, LV_EVENT_ALL, NULL);

}
